### ISSUE TITLE
Синтез речи

### ISSUE THREAD

**Issue by Evghenusi** [veks/button-visually-impaired-javascript#1]
Здравствуйте.
Открываю http://bvi.isvek.ru/  и в консоле браузера пишет:

JQMIGRATE: Migrate is installed, version 1.4.1
ResponsiveVoice r1.5.3
Button visually impaired v1.0.6
**Voice support NOT ready
Voice support NOT ready
Voice support NOT ready
Voice support NOT ready**
RV: speechSynthesis present but no system voices found
RV: Enabling fallback mode

Но при этом нажатие на кнопку "синтез речи" озвучивается, дальше ничего не происходит.
Так и должно быть? На этом всё? Остальной текст не будет озвучиваться?

**Comment by veks** [comment]
Здравствуйте, можете скачать бета версию плагина
https://github.com/veeeeeeeeek/bvi-special .

2018-05-02 12:16 GMT+03:00 Evghenusi <notifications@github.com>:

**Comment by veks** [comment]
> Здравствуйте.
> Открываю http://bvi.isvek.ru/ и в консоле браузера пишет:
> 
> JQMIGRATE: Migrate is installed, version 1.4.1
> ResponsiveVoice r1.5.3
> Button visually impaired v1.0.6
> **Voice support NOT ready Voice support NOT ready Voice support NOT ready Voice support NOT ready**
> RV: speechSynthesis present but no system voices found
> RV: Enabling fallback mode
> 
> Но при этом нажатие на кнопку "синтез речи" озвучивается, дальше ничего не происходит.
> Так и должно быть? На этом всё? Остальной текст не будет озвучиваться?

Ваш браузер не поддерживает синтезатор речи попробуйте обновить.

**Comment by veks** [comment]
В новой версии плагин синтез речи был обновлен.
