### ISSUE TITLE
Тильда (https://tilda.cc/ru/)

### ISSUE THREAD

**Issue by dvdobrovolskiy** [veks/button-visually-impaired-javascript#10]
Тут уже есть Issue по поводу изображений на фоне. Но там несколько задач. 

Тильда, к сожалению, весьма популярный сейчас ресурс и там ВСЕ картинки сделаны background-image:

Данный плагин их затирает, можно как его допилить на этот счет?
http://cetschool.com/

**Comment by veks** [comment]
Добавлена возможность  изменять и показывать background-image
