### ISSUE TITLE
Публикация пакета в NPM

### ISSUE THREAD

**Issue by daks01** [veks/button-visually-impaired-javascript#14]
странно в 21 году вручную качать файлы плагина с гитхаба

**Comment by veks** [comment]
> странно в 21 году вручную качать файлы плагина с гитхаба

Вы думаете публикация пакета в NPM будет актуальна?

**Comment by ProjectSoft-STUDIONIONS** [comment]
> странно в 21 году вручную качать файлы плагина с гитхаба

Вопрос, скорее всего, нужно ставить не "Публикация в NPM", а "Публикация в BOWER". Для bower самое то и да, будет намного удобней.
