### ISSUE TITLE
Не указано семейство шрифтов для плашки плагина

### ISSUE THREAD

**Issue by daks01** [veks/button-visually-impaired-javascript#15]
не во всех операционках установлен Arial
по умолчанию включится serif (с засечками)
и вертел браузер ваш !important 

https://github.com/veks/button-visually-impaired-javascript/blob/a4b5b109fee9576d9bbd87bcec1fccfe43e3f9e9/dist/css/bvi.css#L5

**Comment by veks** [comment]
Для панели шрифт serif не используется

**Comment by veks** [comment]
Смена шрифта в панели не предусмотрена.

**Comment by daks01** [comment]
Шрифт Arial из семейства sans-serif

если явно не указать фалбэк к семейсту шрифта `font-family: Arial, sans-serif !important;` 
то при отсутствие шрифта Arial в системе будет подключен дефолтный шрифт из другого семейства: serif (c засечками)

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#generic-name

**Comment by daks01** [comment]
> Смена шрифта в панели не предусмотрена.

но она происходит неконтролируемо на андроидах, ios, линуксах...
причем меняется не только шрифт, но и семейство
