### ISSUE TITLE
Версия без jQuery

### ISSUE THREAD

**Issue by flystyle** [veks/button-visually-impaired-javascript#16]
Здравствуйте! Не планируете выпустить версию скрипта на чистом JS?

**Comment by veks** [comment]
> Здравствуйте! Не планируете выпустить версию скрипта на чистом JS?

Привет, почти готова версия на чистом JS, возможно через пару месяцев опубликую

**Comment by veks** [comment]
@flystyle, Привет! Готовы новая версия на JavaScript.

**Comment by yaroslavvertukhov** [comment]
@veks Привет. Можете, пожалуйста, залить плагин в NPM?
