### ISSUE TITLE
Неточности в архиве js-плагина

### ISSUE THREAD

**Issue by Ruslan-Aleev** [veks/button-visually-impaired-javascript#22]
Здравствуйте, спасибо за плагин! Часто выручает.

Однако в архиве, который скачивается с https://bvi.isvek.ru/ustanovka-plagina/javascript/ есть несколько ошибок:

1) Не хватает файлов в папке **dist** архива.
На сайте, в пункте "Быстрый старт" указано, мол "... Для активации плагина разместите следующий кусок кода `<script>` в конце страниц, прямо перед закрывающим `</body>`"

```
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://domain.name/js/js.cookie.js"></script>
<script src="https://domain.name/js/bvi-init.js"></script>
<script src="https://domain.name/js/bvi.min.js"></script>
```

Но в архиве нету ни `js.cookie.js`, ни `bvi-init.js`, было бы удобно, если бы требуемые файлы сразу были в архиве (скопировал код, подключил и уже работает).
Если же с jquery понятно, то остальные файлы нужно докачивать отдельно, или создавать, что не удобно.

2) Демо-пример index.html папке **test** архива не работает.
По крайней мере в браузере ошибок нет, но кнопка не работает.

3) Лишняя вложенность папок.
Файлы архива при распаковке лежат внутри `button-visually-impaired-javascript-master`, а эта папка лежит еще в такой же папке `button-visually-impaired-javascript-master`.

4) Стоит добавить в названии архива версию.

**Comment by veks** [comment]
Привет, я знаю что на сайте старая информация, вот тут инструкция
https://github.com/veks/button-visually-impaired-javascript

ср, 8 сент. 2021 г. в 17:15, Ruslan Aleev ***@***.***>:
