### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by LumberTheBlack** [veks/button-visually-impaired-javascript#24]
Доброго времени суток! Уникальный и **чрезвычайно полезный плагин**.
Пытаюсь прикрутить его через webpack encore (на Symfony), (возможно это только у меня) при установке пакета через npm  в пакете не хватает ряда каталогов img (в dist), mixins (в src/scss) и util (в src/js).
Сам плагин после сборки у меня не активировался, полез разбираться и заметил, что при установке document.cookie (метод setCookie, util/cookie.js) в качестве разделителя используется ";" заменил на "," , а в методе getCookie возвращается все, что после bvi_{name}=, в цикле разбора cookies этого метода добавил _let options=cookie.split(",")_ и затем  _return options[0].substring(name.length, options[0].length);_
После этого плагин стал активироваться.
Использованы
  jQuery 3.6.0
 Webpack 5.53.0

**Comment by veks** [comment]
@LumberTheBlack, привет! Исправлю в следующей версии.

**Comment by LumberTheBlack** [comment]
Успехов!
