### ISSUE TITLE
Проблема с работой js версии плагина

### ISSUE THREAD

**Issue by Bital2509** [veks/button-visually-impaired-javascript#27]
Здравствуйте, пытаюсь подключить js версию на свой сайт и пока ничего не выходит. Делал по примеру от сюда.
При нажатии на кнопку сайт перезагружается и все.
В консоли есть такое сообщение Bvi console: ready Button visually impaired v1.0.0 (как я думал если оно выводится значит все ок, но нет) 
Так же в тестовой версии (пример работы в архиве) что с сайта, что с github не работает.
У меня есть вопрос, как я могу применить ваш плагин на своем ресурсе, что надо подправить или скачать ? 
PS jquery подключен (пробовал подключать и на прямую к файлам, и через npm)

**Comment by Bital2509** [comment]
И еще 1 вопрос возник, плагин работает на локалке?
Просто я зашел из другого браузера на локальный проект и он мне выдал "Кука «bvi_panelActive» была отклонена из-за некорректного домена.".
Может это связанно с тем что я локально пытаюсь прикрутить ваш плагин ? (Хотя это странно)

**Comment by Bital2509** [comment]
Короче, разобрался с проблемой.
пришлось изменить немного код bvi.js

1. строка 1040 (Функция setCookie) в 'document.cookie' изменить ';' на ','.
2. В функции getCookie добавить найти цикл и в проверке внутри заменить код на 
`
let options=cookie.split(",")
        return options[0].substring(name.length, options[0].length);
`
3. И в removeCookie сделать замену ';' на ',' как и в 1 действии.

**Comment by sabmile** [comment]
заработало! в связи с чем связано замена ; на , ?

**Comment by Bital2509** [comment]
> заработало! в связи с чем связана замена; на , ?

Честно говоря это было давно и я уже не помню с чем были связаны изменения.
На данный момент я бы сам ручками написал этот функционал (На счет озвучки текста не думал как реализовать)
Если будешь сам писать может сильно помочь tailwindcss (библа мега крутая для стилизации)
Сам по себе этот плагин неплох, но есть много багов и неудобст.
