### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by V1nga** [veks/button-visually-impaired-javascript#44]
Добавил в проект на Nuxt и подключил как написано в readme, в консоль вывелось сообщение что плагин включился, но на кнопку открытия меню никак не реагировал. Решил проверить на чистом html и запустил ваш файлик из папки test, результат тот же самый, сообщение в консоли есть, меню при нажатии на кнопку не отображается.

**Comment by veks** [comment]
Привет, [V1nga](https://github.com/V1nga). Попробуй на локальном сервере или на хостинге.

**Comment by V1nga** [comment]
На веб сервере панелька действительно стала появляться, но видимо с Vuetify происходит какой-то конфликт и весь сайт заливается одним цветом в зависимости от выбранного цвета сайта (белый, чёрный и т.д).

![Screenshot_2](https://user-images.githubusercontent.com/43814565/208386969-6e1e561e-cc7c-4ace-917d-3c5b65142b4d.jpg)

**Comment by ProjectSoft-STUDIONIONS** [comment]
@V1nga что консоль пишет?

**Comment by V1nga** [comment]
@ProjectSoft-STUDIONIONS в консоли только сообщение о успешном запуске плагина, ошибок нет

**Comment by ProjectSoft-STUDIONIONS** [comment]
Тут наверное два выхода.
Либо плагин запускать до рендера Vuetify, либо после.
Либо писать свой компонент рассчитанный под использование с Vuetify.

В остальном только гадать. 
Нужно смотреть рендер элементов и т.д.

**Comment by V1nga** [comment]
Скорее всего второй вариант, я думаю в данной ситуации это проще. Всем спасибо за ответы.

**Comment by MaxDiMart** [comment]
@V1nga , подскажи как ты подключил к проекту библиотеку. Я создал пустое приложение React, подкинул папку dist, подключил скрипт и css. На даже панелька не отображается. На веб-сервере работает.  
Тестовый пример работает только на веб-сервере.

**Comment by Luferov** [comment]
А есть пример подключения к nuxt?
