### ISSUE TITLE
Вкладка зависает при переходе на другую страницу.

### ISSUE THREAD

**Issue by desperadik** [veks/button-visually-impaired-javascript#6]
Привет. 

Спасибо за плагин. Юзал раньше старую версию.

Решил сегодня обновить. 

Вкладка браузера зависает, когда пытаешься перейти на другую страницу сайта с включенным bvi.

GC 73 версия глохнет сразу.

FF 65 после нескольких переходов по сайту.

Ошибок нет. Консоль чистый.

Спасибо.

**Comment by veks** [comment]
ка

> Привет.
> 
> Спасибо за плагин. Юзал раньше старую версию.
> 
> Решил сегодня обновить.
> 
> Вкладка браузера зависает, когда пытаешься перейти на другую страницу сайта с включенным bvi.
> 
> GC 73 версия глохнет сразу.
> 
> FF 65 после нескольких переходов по сайту.
> 
> Ошибок нет. Консоль чистый.
> 
> Спасибо.
Привет, каким браузером пользуетесь, сколько оперативной памяти установлено на вашем компьютере?

**Comment by veks** [comment]
> Привет.
> 
> Спасибо за плагин. Юзал раньше старую версию.
> 
> Решил сегодня обновить.
> 
> Вкладка браузера зависает, когда пытаешься перейти на другую страницу сайта с включенным bvi.
> 
> GC 73 версия глохнет сразу.
> 
> FF 65 после нескольких переходов по сайту.
> 
> Ошибок нет. Консоль чистый.
> 
> Спасибо.

Привет, каким браузером пользуетесь, сколько оперативной памяти установлено на вашем компьютере?

**Comment by despeardik** [comment]
> Привет, каким браузером пользуетесь, сколько оперативной памяти установлено на вашем компьютере?

Google Chrome 73 и Firefox 65.
ОЗУ: 12Гб.

**Comment by veks** [comment]
@desperadik, Проблема еще актуальна?

**Comment by desperadik** [comment]
@veks Уже нет.

**Comment by veks** [comment]
Тема закрыта
