### ISSUE TITLE
Изображения на background

### ISSUE THREAD

**Issue by larinmisha** [veks/button-visually-impaired-javascript#8]
Столкнулся вот с таким вариантом: 
Есть новостная лента, в блоке предназначенном для картинки находится <div> на фоне которого расположена картинка в формате background: url('http://.../1.jpg') center center no-repeat;
Когда запускается плагин то он все background делает выбранного цвета (по умолчанию белый) и там где были фото становятся белые куски. 
Предложение доработать модуль с возможностью либо дописывать какой то класс для таких изображений, либо для всех блоков где был background применять фильтры картинки. Если без фото то рисовать границу (border: 2px dashed !important;), если чёрно-белые картинки то применять фильтр для background. 
Думаю будет удобно и универсально )))

Вторая проблема которую заметил, прячется вот в таких конструкциях 
```
<a class="navbar-brand" href="/">
    <svg>...</svg>
</a>  
```
Данный пример это логотип фирмы с переходом на главную страницу. 
Модуль пытается применить те же правила что и для обычной гиперссылки с текстом, в итоге делает выделение background черным а текст белым, но в данном случае сам логотип svg черный и прозрачный, в итоге получается что выделяется полностью черный блок при наведении. 
Предложение решения такое же, можно предусмотреть класс который будет блокировать какие либо изменения для таких блоков ))) 

p.s. Заранее спасибо, а сам модуль полезен и крут )))

**Comment by veks** [comment]
larimmisha, попробую решить эту проблему в следующем обновлении.

**Comment by Burilmishka** [comment]
@larimmisha, привет можно ли с тобой как-то пообщаться по поводу этого плагина? Не получается подключить, чтобы работал хорошо.

**Comment by larimmisha** [comment]
@Burilmishka, ничего не бывает просто))) Данный модуль хорош (большой плюс к карме разработчика), но каждый сайт написан по своему и идеально данный модуль не встанет, тому пример первое сообщение с предложениями доработки. Лично мне пришлось потратить где то пол дня чтобы готовый сайт доработать под данный плагин (основная проблема была в том что все изображения были на background. И даже тут будет интересно решение (думаю и @veks будет интересно, рядом с блоком где было изображение на фоне я добавил еще <img> тег с той же картинкой, по умолчанию он был скрыт. А встроенными классами bvi-show и bvi-hide я менял их местами, в итоге при переключении в версию для слабовидящих убирались блоки с фоновой картинкой и подключались обычные <img>, но и тут нашлась ошибка, притом плавающая и я ее так и не  придумал как решить. Иногда, при переключении с версии для слабовидящих в обычный режим остаются обе картинки, т.е. bvi-show срабатывает а вот bvi-hide почему не всегда. 
p.s. Ожидаю обновление данного модуля, и попробую еще раз накатить его на сайт, убрав свои костыли временные )))

**Comment by veks** [comment]
Можете писать сюда https://t.me/bviisvek

**Comment by Burilmishka** [comment]
@veks, не могу писать в чат, заблокированы сообщения

**Comment by veks** [comment]
@larinmisha, Попробуй добавить <a class="navbar-brand bvi-show" href="/">

**Comment by veks** [comment]
В новой версии плагина проблема решена?

**Comment by larinmisha** [comment]
Добрый день.
Только сегодня добрался до тестирования новой версии) 
Да, работает круче, но еще есть что можно улучшить)))

Есть класс: 
`html body .bvi-body[data-bvi-theme=white] * {}`
и в нём есть строка: 
`background-color: #fff !important;`
Да, это работает идеально, если background зарисован именно этим свойством, но если к примеру вот такой вариант:
```
.block_text {
    background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.6)), url(.../fon.jpg) no-repeat center top;
    background-size: cover;
} 
```
в этом случае фон не перекрывается, хотя все элементы css из ваших стилей находятся выше чем сам стиль заливки. 
Скриншот со стилями прикрепляю))) 
Для оперативности тестирования, можете писать в телеграмм @larinmisha

![image](https://user-images.githubusercontent.com/17030521/81238153-bb0d9380-901a-11ea-9dfb-d4f52c95dfe4.png)

**Comment by veks** [comment]
Привет @larinmisha, я знаю что эта проблема существует. Идеальное работает с 
`background-image: url(../img.png);`, но тут нужно построить логическую цепочку разных вариантов использования background.

**Comment by larinmisha** [comment]
А стоит ожидать доработку модуля с учётом данной возможности? 
Модуль для сайта шикарен, более лучших реализаций не встречал. Ещё чуть чуть допилить и будет совсем идеальным)))

**Comment by veks** [comment]
@larinmisha, если предоставите тестовый шаблон с разными вариантами **background-image**, то можно и доработать.
